import React from 'react';

const Terms: React.FC = () => (
  <div style={{ fontFamily: 'system-ui, sans-serif', maxWidth: 760, margin: '0 auto', padding: '60px 24px', color: '#0f172a', lineHeight: 1.7 }}>
    <div style={{ marginBottom: 40 }}><a href="/" style={{ color: '#0ea5e9', textDecoration: 'none', fontSize: 14 }}>← Back to PlumbLead.ai</a></div>
    <h1 style={{ fontSize: 32, fontWeight: 800, marginBottom: 8 }}>Terms of Service</h1>
    <p style={{ fontSize: 14, color: '#64748b', marginBottom: 40 }}>Last updated: April 2026 · PlumbLead.ai is operated by K48 Ventures LLC</p>
    <p style={{ marginBottom: 24 }}>These Terms of Service govern your use of PlumbLead.ai and its related services, operated by K48 Ventures LLC. By accessing or using the Service, you agree to be bound by these Terms.</p>

    <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 40, marginBottom: 12 }}>1. Use of the Service</h2>
    <p>PlumbLead.ai provides an AI-powered lead capture and quote generation platform for plumbing contractors and homeowners. You agree to use the Service only for lawful purposes and in accordance with these Terms.</p>

    <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 40, marginBottom: 12 }}>2. Accounts and Access Codes</h2>
    <p>Contractor accounts are provisioned by PlumbLead.ai. You are responsible for maintaining the confidentiality of your access code. Notify us immediately at ryan@plumblead.ai if you suspect unauthorized use of your account.</p>

    <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 40, marginBottom: 12 }}>3. SMS Communications</h2>
    <p>By submitting your phone number through a service request form on PlumbLead.ai or any contractor website powered by PlumbLead.ai, you consent to receive SMS text messages from PlumbLead.ai (program name: <strong>PlumbLead</strong>) related to your service request.</p>
    <p style={{ marginTop: 12 }}><strong>Message types include:</strong> service request confirmations, contractor connection notifications, quote follow-ups, and missed-call recovery alerts.</p>
    <p style={{ marginTop: 12 }}><strong>Message frequency:</strong> Typically 1–3 messages per service request submitted. Frequency varies based on service request activity.</p>
    <p style={{ marginTop: 12 }}><strong>Message and data rates may apply.</strong> Check with your carrier for details.</p>
    <p style={{ marginTop: 12 }}>To opt out at any time, reply <strong>STOP</strong> to any message. You will receive one confirmation message and no further messages will be sent. To request help, reply <strong>HELP</strong> or contact us at ryan@plumblead.ai. Carriers are not liable for delayed or undelivered messages.</p>
    <p style={{ marginTop: 12 }}>We do not share your phone number with third parties for their own marketing purposes. Your information is shared only with the contractor fulfilling your service request.</p>

    <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 40, marginBottom: 12 }}>4. AI-Generated Estimates</h2>
    <p>Price estimates are ballpark ranges generated by artificial intelligence and are not binding quotes. Final pricing is determined by the contractor after reviewing the specific job. PlumbLead.ai makes no warranty regarding estimate accuracy.</p>

    <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 40, marginBottom: 12 }}>5. Contractor Responsibilities</h2>
    <p>Contractors are responsible for verifying their own licensing and insurance, complying with applicable laws, and ensuring pricing accuracy. PlumbLead.ai is a software platform, not a licensed contractor.</p>

    <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 40, marginBottom: 12 }}>6. Subscription and Billing</h2>
    <p>Paid plans are billed monthly. Cancel anytime. Cancellations take effect at the end of the current billing period. No refunds for partial months. Pricing may change with 30 days notice to active subscribers.</p>

    <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 40, marginBottom: 12 }}>7. Limitation of Liability</h2>
    <p>To the maximum extent permitted by law, K48 Ventures LLC and PlumbLead.ai shall not be liable for indirect, incidental, or consequential damages. Total liability for any claim shall not exceed amounts paid in the 3 months preceding the claim.</p>

    <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 40, marginBottom: 12 }}>8. Modifications</h2>
    <p>We reserve the right to update these Terms at any time. Continued use constitutes acceptance. Material changes will be communicated via email to active subscribers.</p>

    <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 40, marginBottom: 12 }}>9. Governing Law</h2>
    <p>These Terms are governed by the laws of the State of Arizona. Any disputes shall be resolved in the courts of Maricopa County, Arizona.</p>

    <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 40, marginBottom: 12 }}>10. Contact</h2>
    <p>K48 Ventures LLC · PlumbLead.ai<br />
    7010 E Acoma Dr Suite 101, Scottsdale, AZ 85254<br />
    Email: <a href="mailto:ryan@plumblead.ai" style={{ color: '#0ea5e9' }}>ryan@plumblead.ai</a><br />
    Phone: <a href="tel:+18335580877" style={{ color: '#0ea5e9' }}>(833) 558-0877</a></p>

    <div style={{ marginTop: 60, paddingTop: 24, borderTop: '1px solid #e2e8f0', fontSize: 13, color: '#94a3b8' }}>
      © 2026 K48 Ventures LLC · PlumbLead.ai &middot; <a href="/privacy" style={{ color: '#94a3b8' }}>Privacy Policy</a>
    </div>
  </div>
);
export default Terms;
